name: Cache
description: Persist cache in between build steps
author: https://github.com/buildkite-plugins
requirements: []
configuration:
  $defs:
    valid_levels:
      type: string
      enum:
        - file
        - step
        - branch
        - pipeline
        - all
  properties:
    backend:
      type: string
    compression:
      type: string
      enum:
        - zip
        - tar
        - tgz
    force:
      type: boolean
    manifest:
      type: string
    path:
      type: string
    restore:
      $ref: '#/$defs/valid_levels'
    save:
      oneOf:
        - $ref: '#/$defs/valid_levels'
        - type: array
          items:
            $ref: '#/$defs/valid_levels'
    fs_copy_tool:
      type: string
      enum:
        - cp
        - rsync
  additionalProperties: false
  anyOf:
    - required: [ path, save ]
    - required: [ path, restore ]

