name: Cache
description: Persist cache in between build steps
author: https://github.com/buildkite-plugins
requirements: []
configuration:
  properties:
    backend:
      type: string
    compression:
      type: string
      enum:
        - zip
        - tar
        - tgz
    manifest:
      type: string
    paths:
      type: array
    restore:
      type: string
      enum:
        - file
        - step
        - branch
        - pipeline
        - all
    save:
      type: string
      enum:
        - file
        - step
        - branch
        - pipeline
        - all
  additionalProperties: false
  required:
    - paths
