steps:
  - label: ":shell: Tests"
    plugins:
      docker-compose#v4.11.0:
        run: tests

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files:
          - hooks/**
          - lib/**
        options: "-x"

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v3.0.0:
        id: cache
