steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.0.0: ~

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/**
            - lib/**
            - backends/**
          options: "-x"

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.2.0:
          id: cache
