#!/bin/bash

CACHE_FOLDER="${BUILDKITE_PLUGIN_FS_CACHE_FOLDER:-/var/cache/buildkite}"

restore_cache() {
  local from="${CACHE_FOLDER}/$1"
  local to="$2"
  cp -av "$from" "$to"
  ls -al "$to"
}

save_cache() {
  local to="${CACHE_FOLDER}/$1"
  local from="$2"
  mkdir -p "$to"
  cp -av "$from" "$to"
  ls -al "$to"
}

exists_cache() {
  local from="${CACHE_FOLDER}/$1"
  [ -e "${from}" ] 
}

if [ "$1" = 'exists' ]; then
  exists_cache "$@"
elif [ "$1" = 'restore' ]; then
  restore_cache "$@"
elif [ "$1" = 'save' ]; then
  save_cache "$@"
fi