#!/bin/bash

if [ -z "${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}" ]; then
  echo '+++ 🚨 Missing S3 bucket configuration'
  exit 1
fi

build_key() {
  if [ -n "${BUILDKITE_PLUGIN_S3_CACHE_PREFIX}" ]; then
    echo "${BUILDKITE_PLUGIN_S3_CACHE_PREFIX}/${1}"
  else
    echo "$1"
  fi
}

s3_cmd() {
  local from="$1"
  local to="$2"
  local use_sync="${3:-1}"

  aws_cmd=(aws s3)

  if [ "${use_sync}" = 'true' ]; then
    aws_cmd+=(sync)
  else
    aws_cmd+=(cp --recursive)
  fi

  if [ -n "${BUILDKITE_PLUGIN_S3_CACHE_ONLY_SHOW_ERRORS}" ]; then
    aws_cmd+=(--only-show-errors)
  fi

  if [ -n "${BUILDKITE_PLUGIN_S3_CACHE_ENDPOINT}" ]; then
    aws_cmd+=(--endpoint-url "${BUILDKITE_PLUGIN_S3_CACHE_ENDPOINT}")
  fi

  "${aws_cmd[@]}" "${from}" "${to}"
}

s3_listobjects() {
  local prefix="$1"

  aws_cmd=(aws s3api list-objects-v2 --bucket "${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}" --prefix "$(build_key "${prefix}")" --max-items 1 --query Contents)

  if [ -n "${BUILDKITE_PLUGIN_S3_CACHE_ENDPOINT}" ]; then
    aws_cmd+=(--endpoint-url "${BUILDKITE_PLUGIN_S3_CACHE_ENDPOINT}")
  fi

  result=$("${aws_cmd[@]}")
  [ "${result}" != 'null' ]
}

restore_cache() {
  local from="$1"
  local to="$2"

  # can not use sync as it may be a single file
  s3_cmd "s3://${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}/$(build_key "${from}")" "${to}" 'false'
}

save_cache() {
  local to="$1"
  local from="$2"
  local use_sync='true'
  if [ -f "${from}" ]; then
    use_sync='false'
  fi

  s3_cmd "${from}" "s3://${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}/$(build_key "${to}")"
}

exists_cache() {
  if [ -z "$1" ]; then exit 1; fi
  s3_listobjects "$1"
}

OPCODE="$1"
shift

if [ "$OPCODE" = 'exists' ]; then
  exists_cache "$@"
elif [ "$OPCODE" = 'get' ]; then
  restore_cache "$@"
elif [ "$OPCODE" = 'save' ]; then
  save_cache "$@"
else
  exit 255
fi
