#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "${DIR}/../lib/shared.bash"

RESTORE_PATH=$(plugin_read_config PATH)

if [ -z "${RESTORE_PATH}" ] ; then
  echo "+++ 🚨 Missing path option in the cache plugin to restore"
  exit 1
fi

MAX_LEVEL=$(plugin_read_config RESTORE 'no')
if [ "${MAX_LEVEL}" = 'no' ]; then
  echo 'Cache not setup for restoring'
  exit 0
elif [ "${MAX_LEVEL}" = 'file' ] && [ -z "$(plugin_read_config MANIFEST)" ]; then
  echo "+++ 🚨 Missing manifest option in the cache plugin for file-level restore"
  exit 1
fi

build_key "${MAX_LEVEL}" "${RESTORE_PATH}" # to validate the level

SORTED_LEVELS=(file step branch pipeline all)

for CURRENT_LEVEL in "${SORTED_LEVELS[@]}"; do
  if [ "${CURRENT_LEVEL}" = 'file' ] && [ -z "$(plugin_read_config MANIFEST)" ]; then
    continue
  fi

  KEY=$(build_key "${CURRENT_LEVEL}" "${RESTORE_PATH}")
  if backend_exec exists "${KEY}"; then
    echo "Cache hit at ${CURRENT_LEVEL} level, restoring ${RESTORE_PATH}..."
    backend_exec get "${KEY}" "${RESTORE_PATH}"
    exit 0
  elif [ "${CURRENT_LEVEL}" = "${MAX_LEVEL}" ]; then
    echo "Cache miss up to ${CURRENT_LEVEL}-level, sorry"
    break
  fi
done
