#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "${DIR}/../lib/shared.bash"

CACHE_PATH=$(plugin_read_config PATH)

if [ -z "${CACHE_PATH}" ] ; then
  echo "+++ 🚨 Missing path option in the cache plugin to save"
  exit 1
fi

LEVEL=$(plugin_read_config SAVE 'no')
if [ "${LEVEL}" = 'no' ]; then
  echo 'Cache not setup for saving'
  exit 0
elif [ "${LEVEL}" = 'file' ] && [ -z "$(plugin_read_config MANIFEST)" ]; then
  echo "+++ 🚨 Missing manifest option in the cache plugin for file-level saving"
  exit 1
fi

KEY=$(build_key "${LEVEL}" "${CACHE_PATH}")

if ! backend_exec exists "${KEY}"; then
  echo 'Saving cache'
  backend_exec save "${KEY}" "${CACHE_PATH}"
else
  echo 'Not saving cache, key already exists'
fi